const HTTP_NOT_FOUND = 404;
const HTTP_BAD_REQUEST = 400;
const HTTP_SERVER_ERROR = 500;
const HTTP_CREATED = 201;

module.exports = {
  HTTP_NOT_FOUND,
  HTTP_BAD_REQUEST,
  HTTP_SERVER_ERROR,
  HTTP_CREATED,
};
